name: Publish Github Proxy Worker

on:
  push:
    branches:
      - '**'

    paths:
      - '**'
      - .cloudflare/workers/github-proxy/**
      - .github/workflows/publish-github-proxy.yml

jobs:
  publish-workers:
    name:    Publish Github Proxy Worker
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delete Existing Worker
        run: 'curl -X DELETE https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/workers/scripts/$SCRIPT_NAME -H "Authorization: Bearer $CF_API_TOKEN"'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SCRIPT_NAME: github-proxy

      - name: Delete Existing KV Store
        run: sudo npm i -g @cloudflare/wrangler; NAMESPACE_ID=`wrangler kv:namespace list | jq -r '.[] | select(.title == '''${SCRIPT_NAME}-kv''').id'`; echo ${SCRIPT_NAME}; echo $NAMESPACE_ID; yes 2>/dev/null | wrangler kv:namespace delete --namespace-id=$NAMESPACE_ID
        working-directory: '.cloudflare/workers/github-proxy'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SCRIPT_NAME: github-proxy

      - name: Init, Plan, Deploy
        run:  set -eux; curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - && sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && sudo apt-get update && sudo apt-get install terraform && terraform init . && terraform plan . && terraform apply --auto-approve .
        working-directory: '.cloudflare/workers/github-proxy'
        env:
          TF_VAR_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          TF_VAR_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
